/// Flutter icons SuccessIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SuccessIcon
///      fonts:
///       - asset: fonts/SuccessIcon.ttf
///
///
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class SuccessIcon {
  SuccessIcon._();

  static const _kFontFam = 'SuccessIcon';
  static const String? _kFontPkg = null;

  static const IconData check_circled =
      IconData(0xf06d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
